const jwt = require('jsonwebtoken');
const moment = require('moment');

/**
 * This function returns a token which is generated by a payload, payload must be
 * an obeject and mus contain at least 1 property.
 * @returns {String} token
 * @param {Object} user
 */
exports.generateToken = (user) => {
    // Create payload with logged user
    const payload = {
        sub: user.user_id,
        name: user.user_name,
        role: user.user_role,
        iat: moment().unix(),
        exp: moment().add(30, 'days').unix()
    };

    // generate and return token
    return jwt.sign(payload, process.env.TOKEN_SECRET);
};
